In this Notebook, we will try to implement a basic PageRank method with the option of random teleportations capability included. The graph that the data is explaining is this graph ![Graph](https://lagunita.stanford.edu/assets/courseware/v1/8f337bcf76940d4679179cde3e3d0364/asset-v1:ComputerScience+MMDS+SelfPaced+type@asset+block/pagerank2.gif)

Suppose we compute PageRank with a β of 0.7, and we introduce the additional constraint that the sum of the PageRanks of the three pages must be 3, to handle the problem that otherwise any multiple of a solution will also be a solution. Compute the PageRanks a, b, and c of the three pages A, B, and C, respectively.

In [1]:
import numpy as np

In [36]:
def pagerank(matrix, initial=None, beta=1, pagerank_sum=1):
    initial = np.ones(len(graph[0]))/len(graph[0]) if initial is None else initial
    qi = initial
    for _ in range(100):
        qi = np.dot((beta)*matrix + (1-beta)*(np.ones_like(matrix)/len(graph[0])), qi);
    return pagerank_sum*qi

In [13]:
graph = np.loadtxt('./input/basicGraph.csv',delimiter=',')

In [14]:
graph

array([[0. , 0. , 0. ],
       [0.5, 0. , 0. ],
       [0.5, 1. , 1. ]])

In [27]:
np.dot(graph,np.array([1/3,1/3,1/3]))

array([0.        , 0.16666667, 0.83333333])

In [37]:
pagerank(graph, beta=0.7, pagerank_sum=3)

array([0.3  , 0.405, 2.295])