In this Notebook, we will try to implement a basic PageRank method with the option of random teleportations capability included. The graph that the data is explaining is this graph ![Graph](https://lagunita.stanford.edu/assets/courseware/v1/8f337bcf76940d4679179cde3e3d0364/asset-v1:ComputerScience+MMDS+SelfPaced+type@asset+block/pagerank2.gif)

Suppose we compute PageRank with a β of 0.7, and we introduce the additional constraint that the sum of the PageRanks of the three pages must be 3, to handle the problem that otherwise any multiple of a solution will also be a solution. Compute the PageRanks a, b, and c of the three pages A, B, and C, respectively.

In [1]:
import numpy as np

In [87]:
def pagerank(matrix, initial=None, beta=1, pagerank_sum=1):
    initial = np.ones(len(graph[0]))/len(graph[0]) if initial is None else initial
    qi = initial
    for _ in range(100):
        qi = np.dot((beta)*matrix + (1-beta)*(np.ones_like(matrix)/len(graph[0])), qi);
    return pagerank_sum*qi

In [13]:
graph = np.loadtxt('./input/basicGraph.csv',delimiter=',')

In [14]:
graph

array([[0. , 0. , 0. ],
       [0.5, 0. , 0. ],
       [0.5, 1. , 1. ]])

In [27]:
np.dot(graph,np.array([1/3,1/3,1/3]))

array([0.        , 0.16666667, 0.83333333])

In [37]:
pagerank(graph, beta=0.7, pagerank_sum=3)

array([0.3  , 0.405, 2.295])

Assuming no "taxation," compute the PageRanks a, b, and c of the three pages A, B, and C, using iteration, starting with the "0th" iteration where all three pages have rank a = b = c = 1. Compute as far as the 5th iteration, and also determine what the PageRanks are in the limit. ![Graph](https://lagunita.stanford.edu/assets/courseware/v1/6c5d817caf80f616e75cc185d6918267/asset-v1:ComputerScience+MMDS+SelfPaced+type@asset+block/pagerank3.gif)

In [62]:
graph2 = np.loadtxt('./input/basicGraph2.csv',delimiter=',')

In [63]:
graph2

array([[0. , 0. , 1. ],
       [0.5, 0. , 0. ],
       [0.5, 1. , 0. ]])

In [68]:
graph2_1 = np.dot(graph2,np.array([1,1,1]))
graph2_1 

array([1. , 0.5, 1.5])

In [71]:
graph2_2 = np.dot(graph2,graph2_1)
graph2_2

array([1. , 1.5, 1. ])

In [70]:
graph2_3 = np.dot(graph2,graph2_2)
graph2_3

array([1.  , 0.75, 1.25])

In [72]:
graph2_4 = np.dot(graph2,graph2_3)
graph2_4

array([1.25, 0.5 , 1.25])

In [73]:
graph2_5 = np.dot(graph2,graph2_4)
graph2_5

array([1.25 , 0.625, 1.125])

In [76]:
graph2_6 = np.dot(graph2,graph2_5)
graph2_6

array([1.125, 0.625, 1.25 ])

The limit of pagerank:

In [88]:
pagerank(graph2, pagerank_sum=3)

array([1.2, 0.6, 1.2])